"""empty message

Revision ID: 4320614d2303
Revises: 4886206438e7
Create Date: 2026-06-11 17:21:04.880325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4320614d2303'
down_revision = '4886206438e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_changes', schema=None) as batch_op:
        batch_op.alter_column('previous_severity',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('low', 'medium', 'high', 'critical', 'none', 'unknown', name='severity_enum'),
               existing_nullable=True)
        batch_op.alter_column('current_severity',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('low', 'medium', 'high', 'critical', 'none', 'unknown', name='severity_enum'),
               existing_nullable=True)
        batch_op.alter_column('previous_affected_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('affected', 'not affected', 'fixed', 'under_investigation', 'accepted_risk', name='status_enum'),
               existing_nullable=True)
        batch_op.alter_column('current_affected_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('affected', 'not affected', 'fixed', 'under_investigation', 'accepted_risk', name='status_enum'),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('vulnerability_changes_previous_snapshot_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('vulnerability_changes_snapshot_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vulnerability_snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vulnerability_snapshots', ['previous_snapshot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('vulnerability_findings', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('low', 'medium', 'high', 'critical', 'none', 'unknown', name='severity_enum'),
               existing_nullable=False)
        batch_op.alter_column('affected_status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('affected', 'not affected', 'fixed', 'under_investigation', 'accepted_risk', name='status_enum'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('vulnerability_findings_snapshot_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vulnerability_snapshots', ['snapshot_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('vulnerability_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_snapshots_product_name'), ['product_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_snapshots_product_version'), ['product_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerability_snapshots_source'), ['source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_snapshots_source'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_snapshots_snapshot_time'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_snapshots_product_version'))
        batch_op.drop_index(batch_op.f('ix_vulnerability_snapshots_product_name'))

    with op.batch_alter_table('vulnerability_findings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vulnerability_findings_snapshot_id_fkey'), 'vulnerability_snapshots', ['snapshot_id'], ['id'])
        batch_op.alter_column('affected_status',
               existing_type=sa.Enum('affected', 'not affected', 'fixed', 'under_investigation', 'accepted_risk', name='status_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', 'none', 'unknown', name='severity_enum'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('vulnerability_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vulnerability_changes_snapshot_id_fkey'), 'vulnerability_snapshots', ['snapshot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('vulnerability_changes_previous_snapshot_id_fkey'), 'vulnerability_snapshots', ['previous_snapshot_id'], ['id'])
        batch_op.alter_column('current_affected_status',
               existing_type=sa.Enum('affected', 'not affected', 'fixed', 'under_investigation', 'accepted_risk', name='status_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('previous_affected_status',
               existing_type=sa.Enum('affected', 'not affected', 'fixed', 'under_investigation', 'accepted_risk', name='status_enum'),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('current_severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', 'none', 'unknown', name='severity_enum'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('previous_severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', 'none', 'unknown', name='severity_enum'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
