"""empty message

Revision ID: 6430e2b237cd
Revises: 
Create Date: 2026-06-05 15:59:48.568284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6430e2b237cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerability_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=128), nullable=False),
    sa.Column('product_version', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('summary_new', sa.Integer(), nullable=False),
    sa.Column('summary_resolved', sa.Integer(), nullable=False),
    sa.Column('summary_severity_changed', sa.Integer(), nullable=False),
    sa.Column('summary_status_changed', sa.Integer(), nullable=False),
    sa.Column('summary_unchanged', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['vulnerability_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_name', 'product_version', 'source', 'snapshot_time', name='uq_vuln_snapshot')
    )
    op.create_table('vulnerability_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('previous_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=64), nullable=True),
    sa.Column('component_name', sa.String(length=128), nullable=True),
    sa.Column('component_version', sa.String(length=64), nullable=True),
    sa.Column('package_url', sa.String(length=255), nullable=True),
    sa.Column('previous_severity', sa.String(length=16), nullable=True),
    sa.Column('current_severity', sa.String(length=16), nullable=True),
    sa.Column('previous_cvss_score', sa.Float(), nullable=True),
    sa.Column('current_cvss_score', sa.Float(), nullable=True),
    sa.Column('previous_affected_status', sa.String(length=32), nullable=True),
    sa.Column('current_affected_status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['vulnerability_snapshots.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vulnerability_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerability_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_changes_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('vulnerability_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('vulnerability_id', sa.String(length=64), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('component_version', sa.String(length=64), nullable=False),
    sa.Column('package_url', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('affected_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['vulnerability_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'vulnerability_id', 'component_name', 'component_version', name='uq_vuln_finding')
    )
    with op.batch_alter_table('vulnerability_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerability_findings_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_findings_snapshot_id'))

    op.drop_table('vulnerability_findings')
    with op.batch_alter_table('vulnerability_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerability_changes_snapshot_id'))

    op.drop_table('vulnerability_changes')
    op.drop_table('vulnerability_snapshots')
    # ### end Alembic commands ###
